### ISSUE TITLE
Not an issue but a lack of knowledge 

### ISSUE THREAD

**Issue by DeadneM** [accelforce/DevOptsHide#2]
Hi I'm not sure what app to select in LSPosed to enable the module properly

**Comment by kyori19** [comment]
Just select apps which is not usable while developer options enabled.
There's no need to select system apps like Settings.

**Comment by DeadneM** [comment]
Mmm i see. That's a problem because when you check an app LSPosed or Edxposed xposed hook the app and the app can detect there's xposed framework. Best exemple i have is Snapchat. If i check Snapchat in LSPosed even i don't have any module doing something to Snapchat the app will say i use xposed. 

Would it be possible to have a whole system hide? 
Like enable the android system in LSPosed will hide devoptions for all app that check it?

**Comment by kyori19** [comment]
I think I can't do that because the only thing I can do is hook some method call (in this module, read access to the system property: is developer options enabled or not) and answer "No" instead of the Android system.
I don't know a way to replace default behaviour of the Android system, but if that is possible, the Settings app will say "Developer options are disabled" so that is completely meaningless...

**Comment by DeadneM** [comment]
Yes that's a vicious circle then. Thanks for clarifying things out for me.
